# Generated by Django 5.1.3 on 2024-12-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0005_delete_categoria_remove_noticia_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='contenido',
            field=models.TextField(default='Sin contenido disponible'),
        ),
    ]
