# Generated by Django 5.1.3 on 2024-12-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0006_noticia_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fuente',
            field=models.CharField(max_length=200),
        ),
    ]
