# Generated by Django 5.1.3 on 2024-12-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0007_alter_noticia_contenido_alter_noticia_fuente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fuente',
            field=models.CharField(default='Desconocida', max_length=255),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
